baseURL = "https://FlippingFlips.github.io/pingod-addons-docs"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "PinGod AddOns"
theme = "hugo-theme-relearn"

hasCJKLanguage = true
metaDataFormat = "yaml"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false


# For search functionality
[outputs]
home = [ "HTML", "RSS", "SEARCH"]

[params]

    # This controls whether submenus will be expanded (true), or collapsed (false) in the
    # menu; if no setting is given, the first menu level is set to false, all others to true;
    # this can be overridden in the pages frontmatter
    alwaysopen = false

    disableOpenapi = true
    showVisitedLinks = true

    author = ""    
    disableSearch = false
    disableSeoHiddenPages = true

    # Source Code repository section
    description = "Documentation for PinGod"
    editURL = "https://github.com/FlippingFlips/pingod-addons-docs/main/docs/content/"
    version = "0.96"

    # Analytic section
    google_analytics_id = "" # Your Google Analytics tracking id
    tag_manager_container_id = "" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification for Search Console

    # Open Graph and Twitter Cards settings section
    # Open Graph settings for each page are set on the front matter.
    # See https://gohugo.io/templates/internal/#open-graph
    # See https://gohugo.io/templates/internal/#twitter-cards
    title = "Hugo Techdoc Theme"
    images = ["images/og-image.png"] # Open graph images are placed in `static/images`

    # Theme settings section
    # Theme color
    # See color value reference https://developer.mozilla.org/en-US/docs/Web/CSS/color
    custom_font_color = "#FFFFFF"
    custom_background_color = "#003300"

    # Documentation Menu section
    # Menu style settings
    menu_style = "slide-menu" # "open-menu" or "slide-menu" or "" blank is as no sidebar

    # Date format
    dateformat = "" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = [
        "archives",
        "archive",
        "blog",
        "entry",
        "post",
        "posts",
    ]

    # Algolia site search section
    # See https://www.algolia.com/doc/
    algolia_search_enable = false
    algolia_indexName = "hugo-demo-techdoc"
    algolia_appId = "7W4SAN4PLK"
    algolia_apiKey = "cbf12a63ff72d9c5dc0c10c195cf9128" # Search-Only API Key

# Global menu section
# See https://gohugo.io/content-management/menus/
[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
        identifier = 'home'
        pre = "<i class='fa fa-house'></i>&nbsp;"

    [[menu.main]]
        name = "Controller"
        url = "https://github.com/FlippingFlips/pingod-controller-com/releases"
        weight = 2
        identifier = 'twitter'
        # pre = "<b>pre!</b> "
        post = " <b>download</b>"
        [menu.main.params]
          class = 'twitter-menu-item'

# Markup configure section
# See https://gohugo.io/getting-started/configuration-markup/
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark.renderer]
        unsafe= true
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6
        ordered = false

# Algolia Search configure section
[outputFormats.Algolia]
    baseName = "algolia"
    mediaType = "application/json"
    isPlainText = true
    notAlternative = true

[params.algolia]
    vars = [
        "title",
        "summary",
        "content",
        "date",
        "publishdate",
        "description",
        "permalink",
        "keywords",
        "lastmod",
    ]
    params = [
        "tags",
        "categories",
    ]
